name: mdrs_simulator
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - apptools=4.4.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - colorama=0.4.3
  - configobj=5.0.6
  - curl=7.64.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - envisage=4.8.0
  - expat=2.2.5
  - freetype=2.9.1
  - future=0.18.2
  - hdf4=4.2.13
  - hdf5=1.8.18
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipyevents=0.7.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - json5=0.9.0
  - jsoncpp=1.8.4
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.2
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - krb5=1.16.4
  - libcurl=7.64.0
  - libiconv=1.15
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.0
  - libtiff=4.1.0
  - libxml2=2.9.9
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - mayavi=4.6.2
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandoc=2.9.1.1
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - pyface=6.1.2
  - pygments=2.5.2
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.6
  - python-dateutil=2.8.1
  - pywin32=225
  - pywinpty=0.5.7
  - pyzmq=18.1.1
  - qt=5.9.7
  - send2trash=1.5.0
  - setuptools=45.2.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - tbb=2020.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - traits=5.2.0
  - traitsui=6.1.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - vtk=8.2.0
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - alabaster==0.7.12
    - astropy==4.0
    - astroquery==0.4
    - babel==2.8.0
    - beautifulsoup4==4.8.2
    - chardet==3.0.4
    - cycler==0.10.0
    - docutils==0.16
    - html5lib==1.0.1
    - idna==2.8
    - imagesize==1.2.0
    - jplephem==2.12
    - keyring==21.1.0
    - kiwisolver==1.1.0
    - llvmlite==0.31.0
    - matplotlib==3.1.3
    - numba==0.48.0
    - packaging==20.1
    - pandas==1.0.1
    - plotly==4.5.0
    - poliastro==0.13.1
    - pyparsing==2.4.6
    - pyqt5==5.14.1
    - pyqt5-sip==12.7.1
    - pytz==2019.3
    - pywin32-ctypes==0.2.0
    - requests==2.22.0
    - retrying==1.3.3
    - scipy==1.4.1
    - snowballstemmer==2.0.0
    - soupsieve==1.9.5
    - sphinx==2.4.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - urllib3==1.25.8