name: mdrs_simulator
channels:
  - conda-forge
dependencies:
  - mayavi=4.7.1
  - astropy==4.0
  - poliastro
  - ipywidgets
  - nodejs
  - ipyevents
  - numpy
  - jupyterlab=1.2.6
  - numba==0.48.0
  - scipy==1.4.1
  - pip:
    - pyqt5==5.14.1
